name: MirakleAI Crawler

on:
  schedule:
    - cron: '0 23 * * *'  # 매일 오전 8시 KST
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with: python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz
      - run: python mirakleai_crawler.py
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
